SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

FPS = 144

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.6 # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PARTICLE_RADIUS = 1

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_MAX_SPEED = 8
PLAYER_ACCELERATION = 3
PLAYER_DECELERATION = .98
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.1

SHOT_RADIUS = 5